#include <stdio.h>

#include <fcntl.h>
#include <unistd.h>
#include <errno.h>
#include <string.h>

//a function that generates and returns a random number by reading in the correct number of bytes from /dev/random
int rand() {
	int file1 = open("/dev/random", O_RDONLY);
	int num[1];
	read(file1, num, sizeof(int));
	return num[0];
}

int main() {
	//populates array with 10 random numbers generated by random fxn
	int arr[10];
	int i;
	for(int i = 0; i < 10; i++) {
		arr[i] = rand();
	}
	
	//print contents of array
	printf("Generating random numbers: \n");
	for(i = 0; i < 10; i++) {
		printf("\t random %d: %d \n", i, arr[i]);
	}
	
	//write array to file without using a loop to write the file
	printf("\nWriting numbers to file...\n");
	int file2 = open("arr.txt", O_CREAT | O_WRONLY, 0644);
	write(file2, arr, sizeof(int) * 10);
	
	//read that file into different array without using a loop
	printf("Reading numbers from file...\n\n");
	int arr2[10];
	file2 = open("arr.txt", O_RDONLY);
	read(file2, arr2, sizeof(int) * 10);
	
	//print contents of second to verify random numbers are same
	printf("Verification that written values were the same: \n");
	for(i = 0; i < 10; i++) {
		printf("\t random %d: %d \n", i, arr2[i]);
	}	
}
